version: '3.2'

volumes:
  jenkins-home:

services:
  jenkins:
    image: ilja07/jenkins-docker
    build: .
    restart: unless-stopped
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    volumes:
#      CHANGE!
      - /Users/iljapavlovs/Desktop/Projects/ilja2/PoC/Jenkins/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: jenkins-docker


